### ISSUE TITLE
Problem when trying to start sdk activity.

### ISSUE THREAD

**Issue by jesustrejo10** [moyasar/moyasar-android-sdk#16]
When trying to start the Payment sheet. I'm getting this exception:

`Unable to start activity ComponentInfo{com.kma.tech.places/com.moyasar.android.sdk.ui.PaymentSheetActivity}: java.lang.RuntimeException: view must have a tag`

To avoid any problem, I followed your sdk instructions seems that the issue is related to data binding.

Some hints, I do have also have stripe sdk integrated into de project.
I created an empty activity just to start the bottom sheet.
I tried with the latest version and some previous one.
Full stack trace.
`ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.kma.tech.places/com.moyasar.android.sdk.ui.PaymentSheetActivity}: java.lang.RuntimeException: view must have a tag
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.RuntimeException: view must have a tag
                                                                                                    	at com.moyasar.android.sdk.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:35)
                                                                                                    	at androidx.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:79)
                                                                                                    	at androidx.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
                                                                                                    	at androidx.databinding.DataBindingUtil.bindToAddedViews(DataBindingUtil.java:327)
                                                                                                    	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:306)
                                                                                                    	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
                                                                                                    	at com.moyasar.android.sdk.ui.PaymentSheetActivity$binding$2.invoke(PaymentSheetActivity.kt:39)
                                                                                                    	at com.moyasar.android.sdk.ui.PaymentSheetActivity$binding$2.invoke(PaymentSheetActivity.kt:38)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.moyasar.android.sdk.ui.PaymentSheetActivity.getBinding(PaymentSheetActivity.kt:38)
                                                                                                    	at com.moyasar.android.sdk.ui.PaymentSheetActivity.onCreate(PaymentSheetActivity.kt:49)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8051)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8031)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)`

**Comment by ahoshaiyan** [comment]
@jesustrejo10 if you have a layout file in your project named `activity_payment_sheet.xml` or any other library has this name, please rename it to avoid this problem
